config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # next line added 7 jul 17 for teacher dashboard (lesson 34)
  resource :dashboard, only: [:show]
  
  # next line added 12 jun 17 to hook up route for landing page
  root "static_pages#index"
  
  # next line added 9 jul 17 for static pages (lesson 39)
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  
  # next 3 lines added 27 jun 17 for student enrollments (lesson 27)
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  
  # next line added 15 jun 17 to hook up route for users page
  resources :users, only: :show
  
  # next line added 16 jun 17 to hook up route for student course pages
  resources :courses, only: [:index, :show]           # student course page

  # next line added 21 jun 17 to hook up route for lesson pages
  resources :lessons, only: [:show]                   # lesson show page
  
  # next line added 16 jun 17 to hook up route for instructor course pages
  namespace :instructor do                            # instructor course page
  # next line added 4 jul 17 for syncing of lesson updates (lesson 31)
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do       # :update added 6 jul 17 for syncing sections (lesson/challenge 32)
      resources :lessons, only: [:create]         # :new removed 9 jul 17 for new lesson form modal (lesson 36)
    end
    resources :courses, only: [:new, :create, :show] do
        
# next line added 17 jun 17 to hook up route for instructor lesson page
      resources :sections, only: [:create, :update]   # :update added 6 jul 17 (lesson/challenge 32), :new deleted 7 jul 17 (lesson 35)
    end
  end
end

app/controllers/courses_controller.rb
# firehose track 4, lesson 15 - file created 16 jun 17 for courses from student perspective

class CoursesController < ApplicationController
  
  def index
    @courses = Course.all
  end
  
  def show
    @course = Course.find(params[:id])
  end
  
end

app/controllers/instructor/courses_controller.rb
# firehose track 4, lesson 13 - file created 16 jun 17 for creating instructor courses

class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  
  # next line added 21 jun 17
  before_action :require_authorized_for_current_course, only: [:show]
  
  def new
    @course = Course.new
  end
  
  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
#    @course = Course.find(params[:id])
# next line added 7 jul 17 for new section form modal (lesson 35)
    @section = Section.new
# next line added 8 jul 17 for new lesson form modal (lesson 36)
     @lesson = Lesson.new
  end


  private
  
# next 9 lines added 21 jun 17
def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end
  
  helper_method :current_course
  
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
  
end

app/controllers/instructor/lessons_controller.rb
# firehose track 4, lesson 18 - file created 17 jun 17 for lessons

class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!       # user must be logged in to access lessons
  before_action :require_authorized_for_current_section, only: [:create]  # :new action removed 9 jul 17 for new lessom form modal (lesson 36) clean-up
  before_action :require_authorized_for_current_lesson, only: [:update]
 
# entire new method deleted 9 jul 17 for new lesson form modal (lesson 36) clean-up, since modal used now
#  def new
#    @section = Section.find(params[:section_id])
# next line added 21 jun 17
#    @section = current_section
#
# next 3 lines added 21 jun 17
#    if current_section.course.user != current_user     # course creator must be current logged-in user to create new lesson
#      return render plain: 'Unauthorized', status: :unauthorized
#    end
#   
#    @lesson = Lesson.new
#  end
  
  def create
#    @section = Section.find(params[:section_id])
# next line added 21 jun 17
#    @section = current_section
    
# next 3 lines added 21 jun 17
#    if current_section.course.user != current_user   # course creator must be current logged-in user to create new lesson
#      return render plain: 'Unauthorized', status: :unauthorized
#    end
    
#    @lesson = @section.lessons.create(lesson_params)
#    redirect_to instructor_course_path(@section.course)
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
    
  end
  
# next 4 lines added 4 jul 17 for syncing lesson updates (lesson 31)
  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated!'
  end

  private
  
# next 8 lines added 4 jul 17 for syncing lesson updates (lesson 31)
  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end
  
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
  
# next 9 lines added 21 jun 17
  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
  
end

app/controllers/instructor/sections_controller.rb
# firehose track 4, lesson 17 - file created 16 jun 17 for instructor sections

class Instructor::SectionsController < ApplicationController
# next 2 lines added 21 jun 17
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create] # :new removed 7 juol 17 (lesson 35)
  before_action :require_authorized_for_current_section, only: [:update] # added 6 jul 17 for syncing section updates (lesson/challenge 32)
  
# new method deleted 7 jul 17 (lesson 35)
#  def new
#    @course = Course.find(params[:course_id])  # modified 21 jun 17
#    @section = Section.new
#  end
  
  def create        # modified 21 jun 17
#    @course = Course.find(params[:course_id])
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end
  
# next 4 lines added 6 jul 17 for syncing section updates (lesson/challenge 32)
  def update
    current_section.update_attributes(section_params)
    render plain: 'updated!'
  end

  private
  
# next 9 lines added 21 jun 17
  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end
  
# next 5 lines added 6 jul 17 for syncing section updates (lesson/challenge 32) (but is this needed?)
  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end
  
  helper_method :current_course
  
  def current_course
#    @current_course ||= Course.find(params[:course_id])  # commented out/next 5 lines added 6 jul 17 for section syncing (lesson/challenge 32)
    if params[:course_id]
      @current_course ||= Course.find(params[:course_id])
    else
      current_section.course
    end
  end

# next 4 lines added 6 jul 17 for section syncing (lesson/challenge 32)  
  helper_method :current_section
  
  def current_section
    section ||= Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)  # :row_order_position added 6 jul 17 for syncing section updates (lesson/challenge 32)
  end
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/new.html.erb
<!-- firehose track 4, lesson 13 - created 16 jun 17 -->

<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    
<!-- next line added 23 jun 17 for image upload, lesson 22 (challenge) -->
    <%= f.input :image %>
    
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<!-- firehose track 4, lesson 13 - file created 16 jun 17 for course show page -->

<!-- next 9 lines added 3 jul 17 (lesson 31) -->
<!-- removed from function below:     $('.lessons li').hide('slow');  -->
<!-- modified 4 jul 17 for lesson 31 -->
<!-- .new-lesson-button block added 8 jul 17 for new lesson form modal (lesson 36) -->
<script>
  $(function() {

    $('.new-lesson-button').click(function( event ) {
      var lessonUrl = $( event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });
    
    $('.lessons').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>

<!-- next 13 lines added 6 jul 17 (lesson/challenge 32) -->
<script>
  $(function() {
    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>

<br />
<div class="booyah-box col-10 offset-1">

<!-- next line added 21 jun 17 -->
  <h1 class="text-center"><%= current_course.title %></h1>
  <br/>

<!-- next line added 24 jun 17 for displaying images - lesson 22 (challenge) -->
  <%= image_tag current_course.image, class: 'img-fluid' %>   <!-- shows image on course page -->
  
<!-- next 2 lines added to preview course page as students would see it -->

<!-- next line added 21 jun 17 -->
  <%= link_to 'Preview As Student...', course_path(current_course), class: 'btn btn-warning float-right' %>
  <br class="clr" />
  
<!-- next 2 lines replaced by 3 lines below them for new section form -->

  <div class="text-center">
    
<!-- Button trigger modal, added 7 jul 17 for new section form modal (lesson 35) -->
  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
    Add a new Section...
  </button>
  
<!-- next line added 21 jun 17, deleted 7 jul 17 (lesson 35) -->


  </div>
  
  <ul class="sections">   <!-- class="sections" added 6 jul 17 for lesson/challenge 32 -->

    <% current_course.sections.rank(:row_order).each do |section| %>   <!-- rank(:row_order) added 6 jul 17 for lesson/challenge 32 -->
      <li data-update-url="<%= instructor_section_path(section) %>" class="section-li">    <!-- data update url added 6 jul 17 (lesson/challenge 32), styling (lesson 33) -->
        <div class="header">    <!-- div added 6 jul 17 (lesson 33) -->
          <span class="fa fa-ellipsis-v"></span>  <!-- added 6 jul 17 for styling instructor page w/3 vertical dots (lesson 33) -->
          <%= section.title %>
        </div>

<!-- Button trigger modal, added 8 jul 17 for new lesson form modal (lesson 36) -->
        <button type="button" class="btn btn-primary btn-lg float-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
          New Lesson...
        </button>

<!-- next lines added 17 jun 17 for lesson form -->

        <br class="clr" />
        <br class="clr" />
        <ul class="lessons">     <!-- class added 3 jul 17 (lesson 31) -->
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url="<%= instructor_lesson_path(lesson) %>">    <!-- data update url added 4 jul 17 (lesson 31) -->
              <div class="row">
                <div class="col-1">
                  <br />
                  <span class="fa fa-ellipsis-v"></span>  <!-- added 6 jul 17 for styling instructor page w/3 vertical dots (lesson 33) -->
                </div>
                <div class="col-11">
<!--            <li data-item-id=<%= lesson.id %>>       data item added 3 jul 17 (lesson 31) -->
                  <p>
                    <b><%= lesson.title %></b>
                  </p>
                  <p>
                    <%= lesson.subtitle %>
                  </p>
                </div>
              </div>
              <br class="clr" />
            </li>
          <% end %>
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>
  
<!-- Modal, added 7 jul 17 for new section form modal (lesson 35) -->
  <div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="newSectionModalLabel">Add a new Section</h4>
        </div>
        <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
          <div class="modal-body">
<!-- next 7 lines (some later deleted) moved here from app/views/instructor/sections/new.html.erb 7 jul 17 (lesson 35) -->
            <%= f.input :title %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Add a section", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<!-- Modal, added 8 jul 17 for new lesson form modal (lesson 36) -->
  <div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="newLessonModalLabel">Add a new Lesson</h4>
        </div>
        <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm' } do |f| %>
          <div class="modal-body">
            <%= f.input :title %>
            <%= f.input :subtitle %>
            <%= f.input :video %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
</div>