config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # next line added 7 jul 17 for teacher dashboard (lesson 34)
  resource :dashboard, only: [:show]
  
  # next line added 12 jun 17 to hook up route for landing page
  root "static_pages#index"
  
  # next line added 9 jul 17 for static pages (lesson 39)
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  
  # next 3 lines added 27 jun 17 for student enrollments (lesson 27)
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  
  # next line added 15 jun 17 to hook up route for users page
  resources :users, only: :show
  
  # next line added 16 jun 17 to hook up route for student course pages
  resources :courses, only: [:index, :show]           # student course page

  # next line added 21 jun 17 to hook up route for lesson pages
  resources :lessons, only: [:show]                   # lesson show page
  
  # next line added 16 jun 17 to hook up route for instructor course pages
  namespace :instructor do                            # instructor course page
  # next line added 4 jul 17 for syncing of lesson updates (lesson 31)
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do       # :update added 6 jul 17 for syncing sections (lesson/challenge 32)
      resources :lessons, only: [:create]         # :new removed 9 jul 17 for new lesson form modal (lesson 36)
    end
    resources :courses, only: [:new, :create, :show] do
        
# next line added 17 jun 17 to hook up route for instructor lesson page
      resources :sections, only: [:create, :update]   # :update added 6 jul 17 (lesson/challenge 32), :new deleted 7 jul 17 (lesson 35)
    end
  end
end

app/controllers/courses_controller.rb
# firehose track 4, lesson 15 - file created 16 jun 17 for courses from student perspective

class CoursesController < ApplicationController
  
  def index
    @courses = Course.all
  end
  
  def show
    @course = Course.find(params[:id])
  end
  
end

app/controllers/instructor/courses_controller.rb
# firehose track 4, lesson 13 - file created 16 jun 17 for creating instructor courses

class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  
  # next line added 21 jun 17
  before_action :require_authorized_for_current_course, only: [:show]
  
  def new
    @course = Course.new
  end
  
  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def show
#    @course = Course.find(params[:id])
# next line added 7 jul 17 for new section form modal (lesson 35)
    @section = Section.new
# next line added 8 jul 17 for new lesson form modal (lesson 36)
     @lesson = Lesson.new
  end


  private
  
# next 9 lines added 21 jun 17
def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end
  
  helper_method :current_course
  
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/views/courses/index.html.erb
<!-- firehose track 4, lesson 15 - file created 16 jun 17 for courses from student perspective -->

<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

<!-- list title/description of each course, w/button -->
  <% @courses.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    <br/>
    
<!-- next line added 24 jun 17 for displaying images - lesson 22 (challenge) -->
    <%= image_tag course.image, class: 'img-fluid' %>   <!-- shows image on index page -->
  
    <div class="row">
      <div class="col-sm-8 col-12">
        <%= course.description %>
      </div>
      <div class="col-sm-4 col-12 text-center">
        <%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
      </div>
    </div>
    <br class="clr" />
  <% end %>
  
</div>

app/views/courses/show.html.erb
<!-- firehose track 4, lesson 16 - file created 16 jun 17 to show course details -->

<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  
<!-- next line added 23 jun 17 for displaying images - lesson 22 (challenge) -->
  <%= image_tag @course.image, class: 'img-fluid' %>   <!-- shows image on course page -->
  
  <br/>
  <div class="row">
    <div class="col-sm-4 col-12 text-center">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>

<!-- allows only course creator to administer course details -->
      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %>
      
<!-- next 3 lines added 27 jun 17 for student enrollment (lesson 27) -->
      <br />
      <br />
<!-- next 3 lines added 27 jun 17 (lesson 27) -->
      <% if current_user %>
        <% if current_user.enrolled_in?(@course) %>
          <h3 class="badge badge-info">You Are Enrolled!</h3>
        <% else %>

<!-- next 3 lines added 28 jun 17 to bypass payment info if course free (lesson 29) -->
          <% if @course.free? %>
            <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
          <% else %>
  
<!-- next lines added 28 jun 17 for accepting payments w/stripe (lesson 29) -->
  
            <%= form_tag course_enrollments_path(@course) do %>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                      data-email="<%= current_user.email %>"
                      data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                      data-amount="<%= (@course.cost * 100).to_i %>"
                      data-locale="auto"></script>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <h3 class="badge badge-info">Sign In to Enroll!</h3>
      <% end %>
    </div>

    <div class="col-sm-8 col-12">
      <%= @course.description %>
    </div>
  </div>
  
<!-- next 16 lines added 21 jun 17 to list course's sections/lessons on course details page -->
  <div class="col-12">
    <% @course.sections.rank(:row_order).each do |section| %>   <!-- rank(:row_order) added 6 jul 17 for lesson/challenge 32 -->
    <br /><br />
      <div class="section">
        <h3><%= section.title %></h3>
        <div class="row">
        <% section.lessons.rank(:row_order).each do |lesson| %>   <!-- added 4 jul 17 for lesson 30 -->
         <div class="col-12 col-sm-6">
          <div class="lesson text-center">
            <br />
            <%= link_to lesson_path(lesson) do %>
              <b><%= lesson.title %></b>
              <br />
              <%= lesson.subtitle %>
            <% end %>
           </div>
          </div>
        <% end %>
       </div>
       <br class="clr" />
      </div>
    <% end %>
  </div>
  
</div>