config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # next line added 7 jul 17 for teacher dashboard (lesson 34)
  resource :dashboard, only: [:show]
  
  # next line added 12 jun 17 to hook up route for landing page
  root "static_pages#index"
  
  # next line added 9 jul 17 for static pages (lesson 39)
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  
  # next 3 lines added 27 jun 17 for student enrollments (lesson 27)
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  
  # next line added 15 jun 17 to hook up route for users page
  resources :users, only: :show
  
  # next line added 16 jun 17 to hook up route for student course pages
  resources :courses, only: [:index, :show]           # student course page

  # next line added 21 jun 17 to hook up route for lesson pages
  resources :lessons, only: [:show]                   # lesson show page
  
  # next line added 16 jun 17 to hook up route for instructor course pages
  namespace :instructor do                            # instructor course page
  # next line added 4 jul 17 for syncing of lesson updates (lesson 31)
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do       # :update added 6 jul 17 for syncing sections (lesson/challenge 32)
      resources :lessons, only: [:create]         # :new removed 9 jul 17 for new lesson form modal (lesson 36)
    end
    resources :courses, only: [:new, :create, :show] do
        
# next line added 17 jun 17 to hook up route for instructor lesson page
      resources :sections, only: [:create, :update]   # :update added 6 jul 17 (lesson/challenge 32), :new deleted 7 jul 17 (lesson 35)
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
<!-- next line added 25 jun 17 for embedding video (lesson 25) -->
    <link href="https://vjs.zencdn.net/5.12.6/video-js.css" rel="stylesheet">
    
  </head>

  <body>

<!-- next line and footer code block added 15 jun 17 for flexbox sticky footer  -->
   <div id="flex-content-container">
    
<!-- next 23 lines added 12 jun 17 for navbar toggler  -->
<!--    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">  default styling  -->

<!-- next line added 12 jun 17 for using inverse navbar w/black background  -->
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
<!--      <a class="navbar-brand" href="#">Flixter</a> -->
<!-- next line added 13 jun 17 for navbar link -->
      <%= link_to 'Flixter', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          
<!-- next 3 lines added 16 jun 17 -->
          <li class="nav-item">
            <%= link_to 'See All Courses', courses_path, class: "nav-link" %>
          </li>
        </ul>

<!-- lines added 13 jun 17  -->
        <ul class="navbar-nav">
          <% if user_signed_in? %>
<!-- next 3 lines added 7 jul 17 for teacher dashboard (lesson 34) -->
          <li class="nav-item">
            <%= link_to 'My Dashboard', dashboard_path, class: "nav-link" %>
          </li>
<!-- next 3 lines added 15 jun 17 for user show page -->
          <li class="nav-item">
            <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
          </li>
            <li class="nav-item">
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
        
      </div>
    </nav>
    
<!-- next 6 lines added 13 jun 17 for devise user authentication -->
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
   </div>
   
   <div id="footer">
      <div class="container">
        
<!-- next lines added 9 jul 17 for finishing footer (lesson 38) -->
        <div class="row">
      <div class="col-12 col-sm-3">
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br />
        <%= link_to 'My Dashboard', dashboard_path %>
      </div>
      <div class="col-12 col-sm-3">
        <b>About</b>
        <br />
        <%= link_to 'Team', team_path %>
        <br />
        <%= link_to 'Careers', careers_path %>
        <br />
        <%= link_to 'Privacy Policy', privacy_path %>
      </div>
      <div class="col-12 col-sm-3">
        <b>Contact</b>
        <br />
        victor.christensen@cox.net
        <br />
<!-- address -->        
        <br />
<!-- address -->   
      </div>
      <div class="col-12 col-sm-3 social">
        <b>Social</b>
        <br />
        <br />
        <%= link_to 'https://github.com/elbereth007' do %>
          <span class="fa fa-github-square fa-2x social-button"></span>
        <% end %>
        <%= link_to 'https://www.linkedin.com/in/victorchristensen/' do %>
          <span class="fa fa-linkedin-square fa-2x social-button"></span>
        <% end %>
        <%= link_to 'https://twitter.com/VicChristensen' do %>
          <span class="fa fa-twitter-square fa-2x social-button"></span>
        <% end %>
      </div>
    </div>
        
<!-- added 16 jun 17 to link to page to create new course, deleted 9 jul 17 for finishing footer (lesson 38)
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %> -->
        
<!-- next 2 lines added 9 jul 17, then deleted for finishing footer (lesson 38)
        <br />
        <%= link_to 'My Dashboard', dashboard_path %> -->
        
      </div>
   </div>
    
<!-- next 2 lines added 25 jun 17 for embedding video (lesson 25) -->
    <script src="https://vjs.zencdn.net/5.12.6/video.js"></script>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  </body>
</html>